import { createHash } from "node:crypto";
import { mkdir, rename, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const assets = [
  {
    url: "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.2.146/pdf.min.js",
    output: "src/generated/pdfjs-main.ts",
    size: 282922,
    sha256: "7662af706ecbf4ae9ba0f4f4ea50636617646c31d6c67aeca2338b1805a11c07",
  },
  {
    url: "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.2.146/pdf.worker.min.js",
    output: "src/generated/pdfjs-worker.ts",
    size: 1074897,
    sha256: "4efa4f25d5f14e309922fb568e3b653ebc53cdb0d60b85bdefd22b30cb0a7a22",
  },
];

for (const asset of assets) {
  const response = await fetch(asset.url, {
    headers: { "user-agent": "OneDrive-Live-MCP deterministic build" },
  });
  if (!response.ok) {
    throw new Error(`Failed to fetch ${asset.url}: HTTP ${response.status}`);
  }
  const bytes = new Uint8Array(await response.arrayBuffer());
  const sha256 = createHash("sha256").update(bytes).digest("hex");
  if (bytes.byteLength !== asset.size || sha256 !== asset.sha256) {
    throw new Error(
      `Pinned PDF.js asset mismatch for ${asset.url}: size=${bytes.byteLength}, sha256=${sha256}`,
    );
  }

  const output = resolve(asset.output);
  const temporary = `${output}.tmp`;
  await mkdir(dirname(output), { recursive: true });
  await writeFile(
    temporary,
    `// Generated by scripts/prepare-pdfjs.mjs. Do not edit.\nexport default ${JSON.stringify(new TextDecoder().decode(bytes))};\n`,
    "utf8",
  );
  await rm(output, { force: true });
  await rename(temporary, output);
}
