import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";
import { ConnectorError } from "./errors";
import { compactVerifiedItem, downloadVerifiedItem, graphFetchBytes, graphResponse, resolveRelativeFolder, resolveRelativeItem, strictRelativePath, validateItemName, verifyItemInsideRoot, type VerifiedItem } from "./graph-core";
import { INTEGRATED_LIMITS, sha256Bytes, toCsv } from "./integrated-core";
import type { IntegrityPlan, PlanAction } from "./integrated-tools";
import { advanceDependencySkips, normalizeProgress, remainingActions, uniqueStrings, upsertFailure, upsertResult } from "./integrity-execution";
import { callIntegrityCoordination, createLeaseFencedStorage, DEFAULT_INTEGRITY_LEASE_SECONDS, type IntegrityOwnerType, type LeaseReference, type ReservationState } from "./integrity-coordination";
import { canonicalJson, errorResult, getArtifact, nowIso, ownedArrayBuffer, putArtifact, sha256HexUtf8, textResult } from "./paid-core";
import { validateComposedPlanActions, type PlanActionLike } from "./prepared-plan-composition";
import { openJson } from "./security";
import type { HotfixContext } from "./version20-hotfix";

const READ_ONLY = { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true } as const;
const NON_DESTRUCTIVE = { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false } as const;
const POLICY = "owner_only_no_sharing_links" as const;
const MAX_BYTES = 4 * 1024 * 1024;
const PLAN = "integrated:plan:";
const OP = "integrated:operation:";

type Prep = {
  version: 1; kind: "document_visual_asset"; preparationId: string; fingerprint: string;
  fingerprintMaterial: Record<string, unknown>; sourceItemId: string; sourcePath: string;
  sourceFilename: string; sourceETag: string; sourceSha256: string; stableVisualKey: string;
  visualSha256: string; format: "jpeg"; mimeType: "image/jpeg"; width: number; height: number;
  byteLength: number; artifactKey: string; provenance: Record<string, unknown>; createdAt: string;
};
type Phase2 = {
  version: 1; actionType: "CREATE_PREPARED_BINARY" | "ENSURE_FOLDER_ACCESS_POLICY" | "VERIFY_ACCESS_POLICY";
  preparationId?: string; preparationFingerprint?: string; destinationPath?: string; proposedFilename?: string;
  expectedFinalSha256?: string; expectedByteLength?: number; expectedFormat?: "jpeg"; expectedWidth?: number;
  expectedHeight?: number; targetPath?: string; policy?: typeof POLICY; provenance?: Record<string, unknown>;
  rightsEvidence?: Record<string, unknown>;
};
type Permission = {
  id?: string; roles?: string[]; inheritedFrom?: unknown; link?: { scope?: string }; invitation?: unknown;
  grantedToV2?: IdentitySet; grantedTo?: IdentitySet; grantedToIdentitiesV2?: IdentitySet[]; grantedToIdentities?: IdentitySet[];
};
type Identity = { id?: string };
type IdentitySet = { user?: Identity; group?: Identity; application?: Identity; siteGroup?: Identity; siteUser?: Identity };
type AccessInternal = { evidence: Record<string, unknown>; satisfied: boolean; removable: string[]; inheritedUnsafe: number; unresolvedDirect: number };
type ExecInput = { executionToken: string; ownerType: IntegrityOwnerType; ownerId: string; invocationId: string; correlationId: string };
type Lease = { planId: string; leaseId: string; fencingToken: number; invocationId: string; ownerType: IntegrityOwnerType; ownerId: string; correlationId: string; recovery?: Record<string, unknown> };

function tool(server: McpServer, name: string): any { return (server as any)._registeredTools?.[name]; }
function data(result: CallToolResult): Record<string, unknown> { return result.structuredContent && typeof result.structuredContent === "object" ? result.structuredContent as Record<string, unknown> : {}; }
function planKey(id: string): string { return `${PLAN}${id}`; }
function opKey(planId: string, actionId: string): string { return `${OP}${planId}:${actionId}`; }
function phase2(action: PlanAction): Phase2 | null {
  const value = action.evidence && typeof action.evidence === "object" ? (action.evidence as any).visualPhase2 : null;
  return value?.version === 1 && ["CREATE_PREPARED_BINARY", "ENSURE_FOLDER_ACCESS_POLICY", "VERIFY_ACCESS_POLICY"].includes(value.actionType) ? value as Phase2 : null;
}
function asError(value: unknown): ConnectorError { return value instanceof ConnectorError ? value : new ConnectorError("visual_phase2_failed", value instanceof Error ? value.message : "Visual Phase 2 failed."); }

export function readJpegProperties(bytes: Uint8Array): { format: "jpeg"; mimeType: "image/jpeg"; width: number; height: number } {
  if (bytes.length < 4 || bytes[0] !== 0xff || bytes[1] !== 0xd8) throw new ConnectorError("visual_format_mismatch", "The exact original is not a JPEG.");
  const sof = new Set([0xc0, 0xc1, 0xc2, 0xc3, 0xc5, 0xc6, 0xc7, 0xc9, 0xca, 0xcb, 0xcd, 0xce, 0xcf]);
  let offset = 2;
  while (offset + 8 < bytes.length) {
    while (offset < bytes.length && bytes[offset] !== 0xff) offset++;
    while (offset < bytes.length && bytes[offset] === 0xff) offset++;
    const marker = bytes[offset++];
    if (marker === 0xd9 || marker === 0xda) break;
    if (marker === 0x01 || marker >= 0xd0 && marker <= 0xd7) continue;
    const length = (bytes[offset] << 8) | bytes[offset + 1];
    if (length < 2 || offset + length > bytes.length) break;
    if (sof.has(marker) && length >= 7) {
      const height = (bytes[offset + 3] << 8) | bytes[offset + 4];
      const width = (bytes[offset + 5] << 8) | bytes[offset + 6];
      if (width && height) return { format: "jpeg", mimeType: "image/jpeg", width, height };
    }
    offset += length;
  }
  throw new ConnectorError("visual_dimensions_unreadable", "The exact JPEG dimensions could not be verified.");
}

function exactPdfJpeg(buffer: ArrayBuffer, key: string): Uint8Array {
  const wanted = /^pdf:image:(\d+):(\d+)$/.exec(key);
  if (!wanted) throw new ConnectorError("stable_visual_key_unsupported", "Only exact PDF JPEG keys in pdf:image:object:generation form are supported by this bounded workflow.");
  const source = new TextDecoder("latin1").decode(buffer);
  for (const match of source.matchAll(/(\d+)\s+(\d+)\s+obj([\s\S]*?)endobj/g)) {
    if (match[1] !== wanted[1] || match[2] !== wanted[2]) continue;
    const body = match[3] ?? "";
    if (!/\/Subtype\s*\/Image\b/.test(body) || !/\/Filter\s*(?:\[\s*)?\/DCTDecode\b/.test(body)) throw new ConnectorError("visual_not_exact_embedded_original", "The stable PDF object is not an unchanged embedded JPEG original.");
    const stream = /stream\r?\n/.exec(body); const end = body.lastIndexOf("endstream");
    if (!stream || end <= stream.index) throw new ConnectorError("visual_stream_unavailable", "The exact embedded JPEG stream is unavailable.");
    const bodyStart = (match.index ?? 0) + match[0].indexOf(body);
    return new Uint8Array(buffer).slice(bodyStart + stream.index + stream[0].length, bodyStart + end);
  }
  throw new ConnectorError("stable_visual_not_found", "The stable visual key was not found in the verified source document.");
}

async function prepPrefix(context: HotfixContext, id: string): Promise<string> { return `preparations/${await sha256HexUtf8(context.userId)}/${id}`; }
export async function prepareDocumentVisualAsset(context: HotfixContext, input: {
  sourceItemId: string; expectedSourceETag: string; expectedSourceSha256: string; stableVisualKey: string;
  expectedVisualSha256: string; expectedFormat: "jpeg" | "jpg"; expectedWidth: number; expectedHeight: number; expectedByteLength: number;
}): Promise<Record<string, unknown>> {
  const verified = await verifyItemInsideRoot(context.env, context.userId, input.sourceItemId);
  if (verified.item.folder || verified.item.eTag !== input.expectedSourceETag) throw new ConnectorError("source_precondition_failed", "The source item or eTag does not match the expected evidence.");
  const source = await downloadVerifiedItem(context.env, context.userId, input.sourceItemId, INTEGRATED_LIMITS.fileBytesMax);
  if (source.verified.item.eTag !== input.expectedSourceETag || await sha256Bytes(source.buffer) !== input.expectedSourceSha256) throw new ConnectorError("source_sha256_mismatch", "The complete current source document does not match the expected evidence.");
  const bytes = exactPdfJpeg(source.buffer, input.stableVisualKey);
  if (bytes.byteLength > MAX_BYTES) throw new ConnectorError("prepared_binary_too_large", "The exact original exceeds the bounded 4 MB workflow limit.");
  const properties = readJpegProperties(bytes); const visualSha = await sha256Bytes(bytes);
  if (visualSha !== input.expectedVisualSha256 || bytes.byteLength !== input.expectedByteLength || properties.width !== input.expectedWidth || properties.height !== input.expectedHeight) throw new ConnectorError("visual_evidence_mismatch", "The exact embedded original does not match the expected hash, length, or dimensions.");
  const material = { version: 1, kind: "document_visual_asset", sourceItemId: verified.item.id, sourcePath: verified.relativePath, sourceFilename: verified.item.name, sourceETag: input.expectedSourceETag, sourceSha256: input.expectedSourceSha256, stableVisualKey: input.stableVisualKey, visualSha256: visualSha, format: "jpeg" as const, mimeType: "image/jpeg" as const, width: properties.width, height: properties.height, byteLength: bytes.byteLength, extractionMethod: "pdf_dct_stream_by_stable_key" };
  const fingerprint = await sha256HexUtf8(canonicalJson(material)); const preparationId = `prep_${fingerprint.slice(0, 48)}`;
  const prefix = await prepPrefix(context, preparationId); const definitionKey = `${prefix}/definition.json`; const artifactKey = `${prefix}/exact-original.jpg`;
  const definition: Prep = { ...material, version: 1, kind: "document_visual_asset", preparationId, fingerprint, fingerprintMaterial: material, artifactKey, provenance: { sourceItemId: verified.item.id, sourceETag: input.expectedSourceETag, sourceSha256: input.expectedSourceSha256, stableVisualKey: input.stableVisualKey, exactOriginalSha256: visualSha, exactOriginalOnly: true, renderOrDerivativeRejected: true }, createdAt: nowIso() };
  let idempotentReplay = false;
  if (await context.env.ARTIFACTS.head(definitionKey)) {
    const existing = JSON.parse(await (await getArtifact(context.env, definitionKey)).text()) as Prep;
    if (existing.fingerprint !== fingerprint || canonicalJson(existing.fingerprintMaterial) !== canonicalJson(material)) throw new ConnectorError("preparation_collision", "The deterministic preparation ID is already bound to different evidence.");
    idempotentReplay = true;
  } else {
    await putArtifact(context.env, artifactKey, bytes, "image/jpeg", { preparationId, fingerprint, sha256: visualSha, sourceItemId: verified.item.id, sourceETag: input.expectedSourceETag, stableVisualKey: input.stableVisualKey });
    await putArtifact(context.env, definitionKey, JSON.stringify(definition, null, 2), "application/json; charset=utf-8", { preparationId, fingerprint, kind: definition.kind });
  }
  const stored = new Uint8Array(await (await getArtifact(context.env, artifactKey)).arrayBuffer());
  if (stored.byteLength !== bytes.byteLength || await sha256Bytes(stored) !== visualSha) throw new ConnectorError("prepared_bytes_changed", "The immutable prepared bytes do not match their definition.");
  return { preparationId, fingerprint, idempotentReplay, source: compactVerifiedItem(source.verified), exactOriginal: { sha256: visualSha, byteLength: bytes.byteLength, ...properties }, provenance: definition.provenance, immutablePrivateR2: true, callerSuppliedBinaryAccepted: false, oneDriveMutationPerformed: false };
}

async function readPrep(context: HotfixContext, id: string, fingerprint: string): Promise<{ definition: Prep; bytes: Uint8Array }> {
  if (!/^prep_[0-9a-f]{48}$/.test(id) || !/^[0-9a-f]{64}$/.test(fingerprint)) throw new ConnectorError("preparation_identifier_invalid", "The preparation ID or fingerprint is invalid.");
  const definition = JSON.parse(await (await getArtifact(context.env, `${await prepPrefix(context, id)}/definition.json`)).text()) as Prep;
  if (definition.kind !== "document_visual_asset" || definition.preparationId !== id || definition.fingerprint !== fingerprint || await sha256HexUtf8(canonicalJson(definition.fingerprintMaterial)) !== fingerprint) throw new ConnectorError("preparation_fingerprint_changed", "The immutable prepared definition does not match the supplied fingerprint.");
  const current = await verifyItemInsideRoot(context.env, context.userId, definition.sourceItemId);
  if (current.item.eTag !== definition.sourceETag) throw new ConnectorError("etag_conflict", "The source document changed after preparation.");
  const bytes = new Uint8Array(await (await getArtifact(context.env, definition.artifactKey)).arrayBuffer());
  const properties = readJpegProperties(bytes);
  if (bytes.byteLength !== definition.byteLength || await sha256Bytes(bytes) !== definition.visualSha256 || properties.width !== definition.width || properties.height !== definition.height) throw new ConnectorError("prepared_bytes_changed", "The prepared exact bytes no longer match their definition.");
  return { definition, bytes };
}

function identitySets(permission: Permission): IdentitySet[] { return [permission.grantedToV2, permission.grantedTo, ...(permission.grantedToIdentitiesV2 ?? []), ...(permission.grantedToIdentities ?? [])].filter(Boolean) as IdentitySet[]; }
export function ownerOnlyPolicySatisfied(input: { permissionCount: number; ownerGrantCount: number; sharingLinkCount: number; directAdditionalGrantCount: number; inheritedUnsafeCount: number; externalPrincipalCount: number; unresolvedPrincipalCount: number }): boolean {
  return input.permissionCount > 0 && input.ownerGrantCount > 0 && input.sharingLinkCount === 0 && input.directAdditionalGrantCount === 0 && input.inheritedUnsafeCount === 0 && input.externalPrincipalCount === 0 && input.unresolvedPrincipalCount === 0;
}
async function inspectInternal(context: HotfixContext, item: VerifiedItem): Promise<AccessInternal> {
  const [me, drive, response] = await Promise.all([graphResponse(context.env, context.userId, "/me?$select=id"), graphResponse(context.env, context.userId, "/me/drive?$select=driveType,owner"), graphResponse(context.env, context.userId, `/me/drive/items/${encodeURIComponent(item.item.id)}/permissions?$select=id,roles,link,invitation,inheritedFrom,grantedToV2,grantedToIdentitiesV2,grantedTo,grantedToIdentities`)]);
  const profile = await me.json() as { id?: string }; const driveInfo = await drive.json() as { driveType?: string; owner?: IdentitySet }; const permissions = ((await response.json()) as { value?: Permission[] }).value ?? [];
  const owners = new Set([profile.id, driveInfo.owner?.user?.id].filter(Boolean) as string[]); if (!owners.size) throw new ConnectorError("owner_identity_unresolved", "The authenticated OneDrive owner could not be safely resolved.");
  let inherited = 0, direct = 0, ownerGrants = 0, links = 0, anonymous = 0, organization = 0, additional = 0, inheritedUnsafe = 0, external = 0, unresolved = 0, unresolvedDirect = 0; const removable: string[] = []; const roles: Record<string, number> = {};
  for (const permission of permissions) {
    const inheritedGrant = Boolean(permission.inheritedFrom); inheritedGrant ? inherited++ : direct++; for (const role of permission.roles ?? []) roles[role] = (roles[role] ?? 0) + 1;
    const sets = identitySets(permission); let owner = false, nonOwner = false, unknown = sets.length === 0;
    for (const set of sets) { if (set.user?.id) owners.has(set.user.id) ? owner = true : (nonOwner = true, external++); else if (set.user) unknown = true; for (const principal of [set.group, set.application, set.siteGroup, set.siteUser]) if (principal) { nonOwner = true; external++; } }
    const link = Boolean(permission.link); const scope = String(permission.link?.scope ?? "").toLowerCase(); if (link) links++; if (scope === "anonymous") anonymous++; if (scope === "organization") organization++; if (permission.invitation) external++;
    if (owner && !nonOwner && !unknown && !link && !permission.invitation) ownerGrants++;
    const unsafe = link || Boolean(permission.invitation) || nonOwner || unknown || !owner; if (unknown) unresolved++;
    if (inheritedGrant && unsafe) inheritedUnsafe++;
    if (!inheritedGrant && unsafe) { additional++; const safeDelete = Boolean(permission.id) && (link || Boolean(permission.invitation) || nonOwner) && (link || (!owner && !unknown)); safeDelete ? removable.push(String(permission.id)) : unresolvedDirect++; }
  }
  const satisfied = ownerOnlyPolicySatisfied({ permissionCount: permissions.length, ownerGrantCount: ownerGrants, sharingLinkCount: links, directAdditionalGrantCount: additional, inheritedUnsafeCount: inheritedUnsafe, externalPrincipalCount: external, unresolvedPrincipalCount: unresolved });
  return { satisfied, removable, inheritedUnsafe, unresolvedDirect, evidence: { item: compactVerifiedItem(item), driveType: String(driveInfo.driveType ?? "unknown"), permissionsInherited: inherited > 0, inheritedPermissionCount: inherited, directPermissionCount: direct, ownerGrantCount: ownerGrants, additionalDirectGrantCount: additional, totalSharingLinkCount: links, anonymousSharingLinkCount: anonymous, organizationWideSharingLinkCount: organization, externalPrincipalCount: external, unresolvedPrincipalCount: unresolved, roleCounts: roles, accessLimitedToAuthenticatedOwner: satisfied, childWouldInheritBroaderAccess: Boolean(item.item.folder) && !satisfied, requestedPolicy: POLICY, requestedPolicySatisfied: satisfied, sanitized: true, tokensExposed: false, graphUrlsExposed: false, principalNamesExposed: false } };
}
export async function inspectItemAccess(context: HotfixContext, input: { itemId?: string; path?: string }): Promise<Record<string, unknown>> {
  if (Boolean(input.itemId) === Boolean(input.path !== undefined)) throw new ConnectorError("access_target_invalid", "Provide exactly one of itemId or path.");
  const item = input.itemId ? await verifyItemInsideRoot(context.env, context.userId, input.itemId) : await resolveRelativeItem(context.env, context.userId, input.path!);
  return (await inspectInternal(context, item)).evidence;
}
async function enforcePolicy(context: HotfixContext, path: string): Promise<Record<string, unknown>> {
  const item = await resolveRelativeItem(context.env, context.userId, path); if (!item.item.folder) throw new ConnectorError("access_policy_target_not_folder", "The owner-only policy target must be a folder.");
  const before = await inspectInternal(context, item); if (before.inheritedUnsafe) throw new ConnectorError("inherited_access_policy_conflict", "Broader inherited access cannot be removed by this bounded action."); if (before.unresolvedDirect) throw new ConnectorError("access_policy_unresolved_grants", "A direct permission could not be safely classified for removal.");
  for (const id of before.removable) { await verifyItemInsideRoot(context.env, context.userId, item.item.id); await graphResponse(context.env, context.userId, `/me/drive/items/${encodeURIComponent(item.item.id)}/permissions/${encodeURIComponent(id)}`, { method: "DELETE" }); }
  const after = await inspectInternal(context, await verifyItemInsideRoot(context.env, context.userId, item.item.id)); if (!after.satisfied) throw new ConnectorError("access_policy_not_satisfied", "Unexpected permissions or links remain after enforcement.");
  return { policy: POLICY, before: before.evidence, after: after.evidence, removedDirectPermissionCount: before.removable.length, accessBroadened: false, verifiedAfterMutation: true };
}
async function verifyPolicy(context: HotfixContext, path: string): Promise<Record<string, unknown>> { const inspection = await inspectInternal(context, await resolveRelativeItem(context.env, context.userId, path)); if (!inspection.satisfied) throw new ConnectorError("access_policy_verification_failed", "The owner-only no-sharing-links policy is not satisfied."); return { policy: POLICY, verification: inspection.evidence, verified: true }; }

export function composeVisualPhase2PlanActions(input: { scopePath: string; structuralActions: Record<string, unknown>[]; preparedBinaryActions: Record<string, unknown>[]; accessActions: Record<string, unknown>[] }): PlanActionLike[] {
  const structural = input.structuralActions.map((action, index) => { if (action.action !== "CREATE_FOLDER" || "content" in action || "bytes" in action) throw new ConnectorError("visual_phase2_structural_action_forbidden", "Only payload-free CREATE_FOLDER structural actions are supported."); return { ...action, operationOrder: Number.isFinite(Number(action.operationOrder)) ? Number(action.operationOrder) : index }; });
  const binary = input.preparedBinaryActions.map((raw, index) => { if ("content" in raw || "bytes" in raw || "binary" in raw) throw new ConnectorError("caller_payload_forbidden", "Caller-supplied binary payloads are forbidden."); const destinationPath = strictRelativePath(String(raw.destinationPath ?? "")); const proposedFilename = validateItemName(String(raw.proposedFilename ?? "")); return { actionId: String(raw.actionId ?? ""), action: "CREATE_PREPARED_BINARY", destinationPath, proposedFilename, dependencies: Array.isArray(raw.dependencies) ? raw.dependencies.map(String) : [], operationOrder: Number.isFinite(Number(raw.operationOrder)) ? Number(raw.operationOrder) : structural.length + index, reason: String(raw.reason ?? "Create one exact immutable prepared visual."), destructive: false, ambiguity: false, finalDecision: "create_prepared_binary_exact", evidence: { ...(raw.evidence && typeof raw.evidence === "object" ? raw.evidence : {}), visualPhase2: { version: 1, actionType: "CREATE_PREPARED_BINARY", preparationId: String(raw.preparationId ?? ""), preparationFingerprint: String(raw.preparationFingerprint ?? ""), destinationPath, proposedFilename, expectedFinalSha256: String(raw.expectedFinalSha256 ?? ""), expectedByteLength: Number(raw.expectedByteLength), expectedFormat: "jpeg", expectedWidth: Number(raw.expectedWidth), expectedHeight: Number(raw.expectedHeight), provenance: raw.provenance && typeof raw.provenance === "object" ? raw.provenance as Record<string, unknown> : {}, rightsEvidence: raw.rightsEvidence && typeof raw.rightsEvidence === "object" ? raw.rightsEvidence as Record<string, unknown> : {} } satisfies Phase2 } }; });
  const access = input.accessActions.map((raw, index) => { const actionType = String(raw.action ?? "") as Phase2["actionType"]; if (!["ENSURE_FOLDER_ACCESS_POLICY", "VERIFY_ACCESS_POLICY"].includes(actionType) || String(raw.policy ?? POLICY) !== POLICY) throw new ConnectorError("access_action_invalid", "Only the named owner-only access actions are supported."); const targetPath = strictRelativePath(String(raw.targetPath ?? "")); return { actionId: String(raw.actionId ?? ""), action: actionType, sourcePath: targetPath, destinationPath: targetPath, dependencies: Array.isArray(raw.dependencies) ? raw.dependencies.map(String) : [], operationOrder: Number.isFinite(Number(raw.operationOrder)) ? Number(raw.operationOrder) : structural.length + binary.length + index, reason: String(raw.reason ?? "Apply or verify owner-only access."), destructive: false, ambiguity: false, finalDecision: actionType.toLowerCase(), evidence: { ...(raw.evidence && typeof raw.evidence === "object" ? raw.evidence : {}), visualPhase2: { version: 1, actionType, targetPath, policy: POLICY } satisfies Phase2 } }; });
  return validateComposedPlanActions(input.scopePath, [...structural, ...binary, ...access]);
}

async function exists(context: HotfixContext, path: string): Promise<VerifiedItem | null> { try { return await resolveRelativeItem(context.env, context.userId, path); } catch (error) { if ((error as any)?.code === "item_not_found") return null; throw error; } }
async function createBinary(context: HotfixContext, definition: Prep, bytes: Uint8Array, destinationPath: string, filename: string): Promise<Record<string, unknown>> {
  const destination = await resolveRelativeFolder(context.env, context.userId, destinationPath); const name = validateItemName(filename); const expectedPath = strictRelativePath(`${destinationPath}/${name}`); if (await exists(context, expectedPath)) throw new ConnectorError("name_conflict", "The exact binary destination already exists."); await verifyItemInsideRoot(context.env, context.userId, destination.item.id);
  const response = await graphResponse(context.env, context.userId, `/me/drive/items/${encodeURIComponent(destination.item.id)}:/${encodeURIComponent(name)}:/content?%40microsoft.graph.conflictBehavior=fail`, { method: "PUT", headers: { "Content-Type": "image/jpeg", "If-None-Match": "*" }, body: new Blob([ownedArrayBuffer(bytes)], { type: "image/jpeg" }) });
  const createdId = String(((await response.json()) as { id?: string }).id ?? ""); const created = createdId ? await verifyItemInsideRoot(context.env, context.userId, createdId) : await resolveRelativeItem(context.env, context.userId, expectedPath); if (created.relativePath !== expectedPath || created.item.folder) throw new ConnectorError("binary_post_write_path_mismatch", "The binary was not created at the exact planned path.");
  const final = new Uint8Array(await graphFetchBytes(context.env, context.userId, `/me/drive/items/${encodeURIComponent(created.item.id)}/content`, MAX_BYTES)); const properties = readJpegProperties(final); const hash = await sha256Bytes(final); if (hash !== definition.visualSha256 || final.byteLength !== definition.byteLength || properties.width !== definition.width || properties.height !== definition.height) throw new ConnectorError("binary_post_write_verification_failed", "The created file differs from the immutable prepared bytes.");
  return { itemId: created.item.id, finalPath: created.relativePath, filename: created.item.name, eTag: created.item.eTag ?? null, exactByteLength: final.byteLength, sha256: hash, format: "jpeg", width: properties.width, height: properties.height, preparationId: definition.preparationId, preparationFingerprint: definition.fingerprint, provenance: definition.provenance, exactBytesVerifiedAfterUpload: true, overwritePermitted: false };
}
async function executeAction(context: HotfixContext, action: PlanAction, meta: Phase2): Promise<Record<string, unknown>> {
  if (meta.actionType === "CREATE_PREPARED_BINARY") { const prepared = await readPrep(context, String(meta.preparationId ?? ""), String(meta.preparationFingerprint ?? "")); if (prepared.definition.visualSha256 !== meta.expectedFinalSha256 || prepared.definition.byteLength !== meta.expectedByteLength || prepared.definition.width !== meta.expectedWidth || prepared.definition.height !== meta.expectedHeight) throw new ConnectorError("prepared_binary_action_mismatch", "The plan action does not match the immutable preparation."); return createBinary(context, prepared.definition, prepared.bytes, String(meta.destinationPath ?? ""), String(meta.proposedFilename ?? "")); }
  if (meta.policy !== POLICY) throw new ConnectorError("access_policy_unsupported", "Only owner_only_no_sharing_links is supported."); return meta.actionType === "ENSURE_FOLDER_ACCESS_POLICY" ? enforcePolicy(context, String(meta.targetPath ?? "")) : verifyPolicy(context, String(meta.targetPath ?? ""));
}
async function verifyPostcondition(context: HotfixContext, meta: Phase2): Promise<{ state: "completed" | "ready_for_retry" | "manual_review"; result?: Record<string, unknown> }> {
  if (meta.actionType === "CREATE_PREPARED_BINARY") { const path = strictRelativePath(`${meta.destinationPath}/${meta.proposedFilename}`); const item = await exists(context, path); if (!item) return { state: "ready_for_retry" }; if (item.item.folder) return { state: "manual_review" }; const bytes = new Uint8Array(await graphFetchBytes(context.env, context.userId, `/me/drive/items/${encodeURIComponent(item.item.id)}/content`, MAX_BYTES)); const properties = readJpegProperties(bytes); const hash = await sha256Bytes(bytes); if (hash !== meta.expectedFinalSha256 || bytes.byteLength !== meta.expectedByteLength || properties.width !== meta.expectedWidth || properties.height !== meta.expectedHeight) return { state: "manual_review" }; return { state: "completed", result: { itemId: item.item.id, finalPath: item.relativePath, filename: item.item.name, eTag: item.item.eTag ?? null, exactByteLength: bytes.byteLength, sha256: hash, format: "jpeg", width: properties.width, height: properties.height, reconciledFromLiveEvidence: true } }; }
  const item = await exists(context, String(meta.targetPath ?? "")); if (!item) return { state: "ready_for_retry" }; const inspection = await inspectInternal(context, item); if (inspection.satisfied) return { state: "completed", result: { policy: POLICY, verification: inspection.evidence, reconciledFromLiveEvidence: true } }; return { state: meta.actionType === "ENSURE_FOLDER_ACCESS_POLICY" ? "ready_for_retry" : "manual_review" };
}
function progress(plan: IntegrityPlan): PlanAction[] { normalizeProgress(plan); advanceDependencySkips(plan); const remaining = remainingActions(plan.actions, plan.completedActions, plan.failedActions, plan.skippedDependencyActions); plan.currentAction = null; plan.nextAction = remaining[0]?.actionId ?? null; if (!remaining.length) { plan.executionStatus = plan.failedActions.length ? "failed" : "completed"; plan.status = plan.executionStatus; if (plan.completedActions.length) plan.auditStatus = "pending"; } else if (plan.completedActions.length || plan.failedActions.length) { plan.executionStatus = "running"; plan.status = "running"; } return remaining; }
async function reconcileOne(context: HotfixContext, plan: IntegrityPlan, action: PlanAction): Promise<"completed" | "ready_for_retry" | "manual_review"> { const meta = phase2(action); if (!meta) return "ready_for_retry"; const checked = await verifyPostcondition(context, meta); if (checked.state === "completed") { const result = { actionId: action.actionId, action: meta.actionType, ...(checked.result ?? {}), completedAt: nowIso(), reconciled: true }; plan.results = upsertResult(plan.results, result); plan.completedActions = uniqueStrings([...plan.completedActions, action.actionId]); plan.failedActions = plan.failedActions.filter((entry) => entry.actionId !== action.actionId); await context.storage.put(opKey(plan.planId, action.actionId), { state: "completed", ...result }); progress(plan); await context.storage.put(planKey(plan.planId), plan); } return checked.state; }
async function acquire(context: HotfixContext, plan: IntegrityPlan, input: ExecInput): Promise<Lease | Record<string, unknown>> { const request = { op: "acquire", planId: plan.planId, scopePath: plan.scopePath, ownerType: input.ownerType, ownerId: input.ownerId, invocationId: input.invocationId, correlationId: input.correlationId, workerVersion: String((context.env as any).WORKER_DEPLOYMENT_ID ?? (context.env as any).WORKER_VERSION ?? "unknown"), leaseDurationSeconds: Number((context.env as any).INTEGRITY_LEASE_SECONDS ?? DEFAULT_INTEGRITY_LEASE_SECONDS) } as const; let result = await callIntegrityCoordination(context.env, context.userId, request); let recovery: Record<string, unknown> | undefined; if (result.recoveryRequired === true) { const id = String(result.previousActionId ?? (result.reservation as any)?.actionId ?? ""); const action = plan.actions.find((candidate) => candidate.actionId === id); if (!action || !phase2(action)) return { ...result, acquired: false, customRecoveryDeferredToExistingExecutor: true }; const state = await reconcileOne(context, plan, action); recovery = { previousActionId: id, reconciliationResult: state, recoveredAt: nowIso() }; result = await callIntegrityCoordination(context.env, context.userId, { ...request, recoveryResolution: recovery }); } if (result.acquired !== true) return { ...result, acquired: false }; return { planId: plan.planId, leaseId: String(result.leaseId), fencingToken: Number(result.fencingToken), invocationId: input.invocationId, ownerType: input.ownerType, ownerId: input.ownerId, correlationId: input.correlationId, recovery }; }
function isLease(value: Lease | Record<string, unknown>): value is Lease { return typeof (value as Lease).leaseId === "string" && Number.isFinite((value as Lease).fencingToken); }
async function release(context: HotfixContext, lease: Lease, outcome: unknown): Promise<void> { await callIntegrityCoordination(context.env, context.userId, { op: "release", planId: lease.planId, leaseId: lease.leaseId, fencingToken: lease.fencingToken, invocationId: lease.invocationId, ownerType: lease.ownerType, ownerId: lease.ownerId, correlationId: lease.correlationId, outcome }); }

async function executeCustom(context: HotfixContext, input: ExecInput, token: { planId: string; planHash: string }): Promise<Record<string, unknown>> {
  let plan = await context.storage.get<IntegrityPlan>(planKey(token.planId)); if (!plan || Date.parse(plan.expiresAt) <= Date.now()) throw new ConnectorError("plan_not_found", "The plan does not exist or has expired."); if (plan.validationStatus !== "valid" || plan.planHash !== token.planHash) throw new ConnectorError("plan_not_validated", "The plan is not currently validated."); const action = remainingActions(plan.actions, plan.completedActions, plan.failedActions, plan.skippedDependencyActions)[0]; const meta = action ? phase2(action) : null; if (!action || !meta) throw new ConnectorError("custom_action_not_ready", "No visual Phase 2 action is ready.");
  const acquired = await acquire(context, plan, input); if (!isLease(acquired)) return { ...acquired, planId: plan.planId, leaseAcquired: false, completedThisInvocation: [], failedThisInvocation: [], resumeRequired: true }; const ref: LeaseReference = { planId: acquired.planId, leaseId: acquired.leaseId, fencingToken: acquired.fencingToken, invocationId: acquired.invocationId }; const fenced: HotfixContext = { ...context, storage: createLeaseFencedStorage(context.storage, context.env, context.userId, ref) }; let reservation: Record<string, unknown> | null = null;
  try {
    if (String(acquired.recovery?.reconciliationResult ?? "") === "completed") { await release(context, acquired, { recoveryReconciledAction: acquired.recovery }); const recovered = await context.storage.get<IntegrityPlan>(planKey(plan.planId)) ?? plan; const left = remainingActions(recovered.actions, recovered.completedActions, recovered.failedActions, recovered.skippedDependencyActions); return { planId: recovered.planId, executionState: left.length ? "reconciled" : "complete", leaseAcquired: true, reconciledThisInvocation: [action.actionId], completedThisInvocation: [], failedThisInvocation: [], remainingActions: left.length, nextAction: left[0]?.actionId ?? null, resumeRequired: left.length > 0 }; }
    if (["manual_review", "failed_closed"].includes(String(acquired.recovery?.reconciliationResult ?? ""))) { await release(context, acquired, { recoveryBlockedExecution: acquired.recovery }); return { planId: plan.planId, executionState: acquired.recovery?.reconciliationResult, leaseAcquired: true, completedThisInvocation: [], failedThisInvocation: [], resumeRequired: true }; }
    reservation = (await callIntegrityCoordination(context.env, context.userId, { op: "reserve", ...ref, ownerType: acquired.ownerType, ownerId: acquired.ownerId, correlationId: acquired.correlationId, actionId: action.actionId, expectedPreconditions: { dependencies: action.dependencies ?? [], preparationId: meta.preparationId ?? null, fingerprint: meta.preparationFingerprint ?? null, policy: meta.policy ?? null }, intendedPostcondition: { action: meta.actionType, path: meta.destinationPath ?? meta.targetPath ?? null, filename: meta.proposedFilename ?? null, sha256: meta.expectedFinalSha256 ?? null } })).reservation as Record<string, unknown>;
    await callIntegrityCoordination(context.env, context.userId, { op: "mark-mutation-started", ...ref, actionId: action.actionId, progressSequence: Number(reservation?.attempt ?? 1), leaseDurationSeconds: Number((context.env as any).INTEGRITY_LEASE_SECONDS ?? DEFAULT_INTEGRITY_LEASE_SECONDS) }); await fenced.storage.put(opKey(plan.planId, action.actionId), { state: "prepared", preparedAt: nowIso(), action, phase2: meta }); const result = await executeAction(fenced, action, meta); const completed = { actionId: action.actionId, action: meta.actionType, ...result, completedAt: nowIso() }; await fenced.storage.put(opKey(plan.planId, action.actionId), { state: "completed", ...completed }); plan = await fenced.storage.get<IntegrityPlan>(planKey(plan.planId)) ?? plan; plan.results = upsertResult(plan.results, completed); plan.completedActions = uniqueStrings([...plan.completedActions, action.actionId]); plan.failedActions = plan.failedActions.filter((entry) => entry.actionId !== action.actionId); plan.completedInvocations = Number(plan.completedInvocations ?? 0) + 1; plan.lastExecutionAt = nowIso(); const left = progress(plan); await fenced.storage.put(planKey(plan.planId), plan); await callIntegrityCoordination(context.env, context.userId, { op: "finalize-action", ...ref, actionId: action.actionId, reservationState: "completed", outcome: { completed: [action.actionId], idempotencyKey: reservation?.idempotencyKey ?? null } }); await release(context, acquired, { state: "completed", actionId: action.actionId }); return { planId: plan.planId, status: plan.status, executionStatus: plan.executionStatus, executionState: left.length ? "yielded" : "complete", leaseAcquired: true, leaseId: acquired.leaseId, fencingToken: acquired.fencingToken, currentAction: action.actionId, completedThisInvocation: [action.actionId], failedThisInvocation: [], remainingActions: left.length, nextAction: left[0]?.actionId ?? null, resumeRequired: left.length > 0, results: plan.results };
  } catch (error) {
    const safe = asError(error); plan = await fenced.storage.get<IntegrityPlan>(planKey(plan.planId)) ?? plan; plan.failedActions = upsertFailure(plan.failedActions, { actionId: action.actionId, code: safe.code, message: safe.message, retryable: safe.retryable, status: safe.status, correlationId: safe.correlationId, details: safe.details }); plan.completedInvocations = Number(plan.completedInvocations ?? 0) + 1; plan.lastExecutionAt = nowIso(); const left = progress(plan); await fenced.storage.put(opKey(plan.planId, action.actionId), { state: "failed", failedAt: nowIso(), action, phase2: meta, error: { code: safe.code, message: safe.message, retryable: safe.retryable, details: safe.details ?? null } }).catch(() => undefined); await fenced.storage.put(planKey(plan.planId), plan).catch(() => undefined); const state: ReservationState = /mismatch|conflict|unresolved/.test(safe.code) ? "manual_review" : "failed"; if (reservation) await callIntegrityCoordination(context.env, context.userId, { op: "finalize-action", ...ref, actionId: action.actionId, reservationState: state, outcome: { failed: [action.actionId], code: safe.code } }).catch(() => undefined); await release(context, acquired, { state, actionId: action.actionId }).catch(() => undefined); return { planId: plan.planId, executionState: state, leaseAcquired: true, currentAction: action.actionId, completedThisInvocation: [], failedThisInvocation: [action.actionId], remainingActions: left.length, nextAction: left[0]?.actionId ?? null, resumeRequired: true, failedActions: plan.failedActions, error: { code: safe.code, message: safe.message, retryable: safe.retryable, correlationId: safe.correlationId } };
  }
}

async function reconcileCustom(context: HotfixContext, input: { planId: string; maximumActions?: number; ownerId?: string; invocationId?: string; correlationId?: string }): Promise<Record<string, unknown>> {
  const plan = await context.storage.get<IntegrityPlan>(planKey(input.planId)); if (!plan) throw new ConnectorError("plan_not_found", "The plan was not found."); const actions = remainingActions(plan.actions, plan.completedActions, plan.failedActions, plan.skippedDependencyActions).filter((action) => Boolean(phase2(action))).slice(0, Math.min(Math.max(Number(input.maximumActions ?? 3), 1), 3)); if (!actions.length) return { customActionsFound: false };
  const acquired = await acquire(context, plan, { executionToken: "", ownerType: "internal_job", ownerId: input.ownerId ?? "visual_phase2_reconcile", invocationId: input.invocationId ?? crypto.randomUUID(), correlationId: input.correlationId ?? `visual-phase2-reconcile:${input.planId}` }); if (!isLease(acquired)) return { ...acquired, customActionsFound: true }; const ref: LeaseReference = { planId: acquired.planId, leaseId: acquired.leaseId, fencingToken: acquired.fencingToken, invocationId: acquired.invocationId }; const fenced: HotfixContext = { ...context, storage: createLeaseFencedStorage(context.storage, context.env, context.userId, ref) }; const reconciled: string[] = []; let discrepancy: Record<string, unknown> | null = null;
  try { let current = await fenced.storage.get<IntegrityPlan>(planKey(plan.planId)) ?? plan; for (const action of actions) { const state = await reconcileOne(fenced, current, action); current = await fenced.storage.get<IntegrityPlan>(planKey(plan.planId)) ?? current; if (state === "completed") reconciled.push(action.actionId); else if (state === "manual_review") { discrepancy = { actionId: action.actionId, code: "custom_postcondition_mismatch" }; break; } } return { planId: plan.planId, customActionsFound: true, reconciledThisInvocation: reconciled, discrepancy, leaseAcquired: true, fencingToken: acquired.fencingToken }; } finally { await release(context, acquired, { reconciliationOnly: true, reconciled }).catch(() => undefined); }
}

function augmentDiff(result: Record<string, unknown>, plan: IntegrityPlan): Record<string, unknown> { const custom = plan.actions.map((action) => ({ action, meta: phase2(action) })).filter((entry): entry is { action: PlanAction; meta: Phase2 } => Boolean(entry.meta)); const paths = new Set(custom.filter((entry) => entry.meta.actionType === "CREATE_PREPARED_BINARY").map((entry) => strictRelativePath(`${entry.meta.destinationPath}/${entry.meta.proposedFilename}`).toLowerCase())); const unexpected = result.unexpectedChanges && typeof result.unexpectedChanges === "object" ? { ...(result.unexpectedChanges as Record<string, unknown>) } : {}; if (Array.isArray(unexpected.addedItems)) unexpected.addedItems = unexpected.addedItems.filter((item) => !paths.has(String((item as any)?.relativePath ?? "").toLowerCase())); return { ...result, expectedChanges: [...(Array.isArray(result.expectedChanges) ? result.expectedChanges : []), ...custom.map(({ action, meta }) => ({ actionId: action.actionId, action: meta.actionType, destinationPath: meta.destinationPath ?? meta.targetPath ?? null, proposedFilename: meta.proposedFilename ?? null, policy: meta.policy ?? null }))], unexpectedChanges: unexpected, visualPhase2AccessVerifications: plan.results.filter((entry) => ["ENSURE_FOLDER_ACCESS_POLICY", "VERIFY_ACCESS_POLICY"].includes(String(entry.action ?? ""))), visualPhase2ExactBinaryResults: plan.results.filter((entry) => String(entry.action ?? "") === "CREATE_PREPARED_BINARY") }; }

const structureSchema = z.object({ actionId: z.string().min(1).max(200), action: z.literal("CREATE_FOLDER"), destinationPath: z.string().max(1000), proposedFilename: z.string().min(1).max(255), dependencies: z.array(z.string().min(1).max(200)).max(500).default([]), operationOrder: z.number().int().min(0).optional(), reason: z.string().max(5000).optional(), evidence: z.record(z.string(), z.unknown()).optional(), content: z.never().optional(), bytes: z.never().optional() }).strict();
const binarySchema = z.object({ preparationId: z.string().regex(/^prep_[0-9a-f]{48}$/), preparationFingerprint: z.string().regex(/^[0-9a-f]{64}$/), actionId: z.string().min(1).max(200), destinationPath: z.string().max(1000), proposedFilename: z.string().min(1).max(255), dependencies: z.array(z.string().min(1).max(200)).max(500).default([]), operationOrder: z.number().int().min(0).optional(), expectedFinalSha256: z.string().regex(/^[0-9a-f]{64}$/), expectedByteLength: z.number().int().positive().max(MAX_BYTES), expectedFormat: z.enum(["jpeg", "jpg"]), expectedWidth: z.number().int().positive().max(16384), expectedHeight: z.number().int().positive().max(16384), reason: z.string().max(5000).optional(), provenance: z.record(z.string(), z.unknown()), rightsEvidence: z.record(z.string(), z.unknown()), evidence: z.record(z.string(), z.unknown()).optional(), content: z.never().optional(), bytes: z.never().optional(), binary: z.never().optional() }).strict();
const accessSchema = z.object({ actionId: z.string().min(1).max(200), action: z.enum(["ENSURE_FOLDER_ACCESS_POLICY", "VERIFY_ACCESS_POLICY"]), targetPath: z.string().min(1).max(1000), policy: z.literal(POLICY).default(POLICY), dependencies: z.array(z.string().min(1).max(200)).max(500).default([]), operationOrder: z.number().int().min(0).optional(), reason: z.string().max(5000).optional(), evidence: z.record(z.string(), z.unknown()).optional() }).strict();

export function registerVisualPhase2Tools(server: McpServer, contextFactory: () => HotfixContext): void {
  server.registerTool("prepare_document_visual_asset", { title: "Prepare exact document visual asset", description: "Verify one source PDF and one unchanged embedded JPEG original, then store the exact bytes immutably in private R2 without mutating OneDrive.", inputSchema: { sourceItemId: z.string().min(1).max(500), expectedSourceETag: z.string().min(1).max(1000), expectedSourceSha256: z.string().regex(/^[0-9a-f]{64}$/), stableVisualKey: z.string().regex(/^pdf:image:\d+:\d+$/), expectedVisualSha256: z.string().regex(/^[0-9a-f]{64}$/), expectedFormat: z.enum(["jpeg", "jpg"]), expectedWidth: z.number().int().positive().max(16384), expectedHeight: z.number().int().positive().max(16384), expectedByteLength: z.number().int().positive().max(MAX_BYTES), bytes: z.never().optional(), content: z.never().optional() }, annotations: NON_DESTRUCTIVE }, async (input) => { try { return textResult(await prepareDocumentVisualAsset(contextFactory(), input)); } catch (error) { return errorResult(error); } });
  server.registerTool("inspect_item_access", { title: "Inspect sanitized OneDrive access", description: "Inspect inherited/direct grants, sharing links, external principals, owner-only access, and child inheritance without exposing identities, tokens, or Graph URLs.", inputSchema: { itemId: z.string().min(1).max(500).optional(), path: z.string().max(1000).optional(), requestedPolicy: z.literal(POLICY).default(POLICY) }, annotations: READ_ONLY }, async ({ itemId, path }) => { try { return textResult(await inspectItemAccess(contextFactory(), { itemId, path })); } catch (error) { return errorResult(error); } });
  const createPlan = tool(server, "create_integrity_plan")?.handler; if (!createPlan) throw new Error("create_integrity_plan must be registered before visual Phase 2 composition tools.");
  server.registerTool("commit_visual_phase2_integrity_plan", { title: "Compose visual Phase 2 integrity plan", description: "Create one non-executed integrity plan containing exact prepared-binary creation and owner-only access-policy actions. Binary bytes are obtained only from immutable preparation.", inputSchema: { snapshotId: z.string().uuid(), scopePath: z.string().max(1000), structuralActions: z.array(structureSchema).max(100).default([]), preparedBinaryActions: z.array(binarySchema).min(1).max(100), accessActions: z.array(accessSchema).min(1).max(100), reason: z.string().min(1).max(5000).default("Create a non-executed visual Phase 2 plan with exact assets and owner-only access controls.") }, annotations: NON_DESTRUCTIVE }, async (input) => { try { const actions = composeVisualPhase2PlanActions(input); const result = await createPlan({ snapshotId: input.snapshotId, scopePath: input.scopePath, actions }, {}) as CallToolResult; if (result.isError) return result; return textResult({ ...data(result), actionCount: actions.length, exactPreparedBinaryActionCount: input.preparedBinaryActions.length, accessPolicyActionCount: input.accessActions.length, structuralActionCount: input.structuralActions.length, composedBy: "visual_phase2_prepared_plan_extension", callerSuppliedBinaryAccepted: false, oneDriveMutationPerformed: false, semanticPlanActions: actions.map((action) => ({ actionId: action.actionId, action: phase2(action as PlanAction)?.actionType ?? action.action, dependencies: action.dependencies ?? [] })), planCsvPreview: toCsv(actions as Array<Record<string, unknown>>) }); } catch (error) { return errorResult(error); } });
  const execute = tool(server, "execute_integrity_plan"); if (execute?.handler && !execute.__visualPhase2Wrapped) { const original = execute.handler.bind(execute); execute.handler = async (input: ExecInput) => { try { const token = await openJson<{ planId: string; planHash: string; expiresAt: number }>(contextFactory().env.COOKIE_ENCRYPTION_KEY, String(input.executionToken ?? "")).catch(() => null); if (!token || token.expiresAt <= Date.now()) return original(input, {}); const plan = await contextFactory().storage.get<IntegrityPlan>(planKey(token.planId)); const ready = plan ? remainingActions(plan.actions, plan.completedActions, plan.failedActions, plan.skippedDependencyActions) : []; return ready[0] && phase2(ready[0]) ? textResult(await executeCustom(contextFactory(), input, token)) : original(input, {}); } catch (error) { return errorResult(error); } }; execute.__visualPhase2Wrapped = true; }
  const reconcile = tool(server, "reconcile_integrity_plan"); if (reconcile?.handler && !reconcile.__visualPhase2Wrapped) { const original = reconcile.handler.bind(reconcile); reconcile.handler = async (input: any) => { try { const result = await reconcileCustom(contextFactory(), input); return result.customActionsFound === false ? original(input, {}) : textResult(result); } catch (error) { return errorResult(error); } }; reconcile.__visualPhase2Wrapped = true; }
  const diff = tool(server, "diff_scope_before_after"); if (diff?.handler && !diff.__visualPhase2Wrapped) { const original = diff.handler.bind(diff); diff.handler = async (input: { planId: string }) => { try { const result = await original(input, {}) as CallToolResult; if (result.isError) return result; const plan = await contextFactory().storage.get<IntegrityPlan>(planKey(input.planId)); return !plan || !plan.actions.some((action) => Boolean(phase2(action))) ? result : textResult(augmentDiff(data(result), plan)); } catch (error) { return errorResult(error); } }; diff.__visualPhase2Wrapped = true; }
}
